version: '3.8'

services:
  db:
    image: postgres:15
    user: root
    container_name: postgres_db
    restart: always
    env_file:
    - .env
    volumes:
    - ./my_dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      PGDATA: /tmp
  
  redis:
    image: redis:7
    user: root
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  postgres_data:
